// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJgTKdzil-b15hhuu_5SbDqVeU4HQpkqw',
    appId: '1:391071227179:web:49f02d95309085c83b396e',
    messagingSenderId: '391071227179',
    projectId: 'flowerone',
    authDomain: 'flowerone.firebaseapp.com',
    storageBucket: 'flowerone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1G_6SvjMsy9rd4flYUDUYBtjcI3QmE0Y',
    appId: '1:391071227179:android:9d83284bb87b63323b396e',
    messagingSenderId: '391071227179',
    projectId: 'flowerone',
    storageBucket: 'flowerone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMhDSUP1C7Jz92CEjyzKFysi2IXlhXOw',
    appId: '1:391071227179:ios:f7c288b6fd2576583b396e',
    messagingSenderId: '391071227179',
    projectId: 'flowerone',
    storageBucket: 'flowerone.firebasestorage.app',
    iosBundleId: 'com.o06.flowerone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgMhDSUP1C7Jz92CEjyzKFysi2IXlhXOw',
    appId: '1:391071227179:ios:f7c288b6fd2576583b396e',
    messagingSenderId: '391071227179',
    projectId: 'flowerone',
    storageBucket: 'flowerone.firebasestorage.app',
    iosBundleId: 'com.o06.flowerone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJgTKdzil-b15hhuu_5SbDqVeU4HQpkqw',
    appId: '1:391071227179:web:4940da2b896b52a93b396e',
    messagingSenderId: '391071227179',
    projectId: 'flowerone',
    authDomain: 'flowerone.firebaseapp.com',
    storageBucket: 'flowerone.firebasestorage.app',
  );

}